[package]
name = "cli"
version = "1.1.1"
edition = "2024"

[dependencies]
getopts = "0.2.21"
glob = "0.3.1"
ratatui = "0.29.0"
rusqlite = "0.33.0"
strum_macros = "0.26"
textwrap = "0.16.1"
unicode-width = "0.2.0"
